import turtle
myTurtle = turtle.Turtle()
myTurtle.forward(50)
myTurtle.right(60)
myTurtle.forward(50)
myTurtle.right(60)
myTurtle.forward(50)
myTurtle.right(60)
myTurtle.forward(50)
myTurtle.right(60)
myTurtle.forward(50)
myTurtle.right(60)
myTurtle.forward(50)